- .travis.yml
- civo/provider.go
- civo/resource_instance.go
- civo/resource_network.go
- civo/resource_volume.go
- civo/utils.go
- go.mod
- go.sum
- main.go
- Change .travis.yml to use Go 1.13
Signed-off-by: Alejandro JNM <alejandrojnm@gmail.com>
> - Rename provider folder to civo

- .goreleaser.yml
- Added .goreleaser.yml to the project
> feat: Add goreleaser conf

- civo/resource_firewall_rule.go
- website/docs/r/firewall_rule.html.markdown
Change cird for cidr in the firewall rule
> Fix a type error in the firewall

- civo/resource_instance.go
- website/docs/r/instance.html.markdown
- Added support to add script at the moment of create the instances
- Update the documentation of the instance
> added support to add script

- civo/resource_kubernetes_cluster.go
- go.sum
> Error message when changing Kubernetes nodes size

- civo/resource_kubernetes_cluster_nodepool.go
- docs/resources/kubernetes_node_pool.md
> Fix imported node pool's scaling issue

- civo/resource_kubernetes_cluster.go
> Change default node size to "g3.k3s.medium"

- civo/resource_firewall_rule.go
- docs/resources/firewall_rule.md
> Make CIDR required in 'civo_firewall_rule'

- civo/datasource_network.go
- civo/resource_volume.go
> Allow network datasource query by ID/label/region

- civo/resource_kubernetes_cluster.go
> Save cluster tags in space separated format

- civo/resource_kubernetes_cluster.go
> Set `firewall_id` in cluster resource as computed

- civo/resource_instance.go
- docs/resources/instance.md
> Remove "move IP" from schema and docs

- civo/resource_firewall_rule.go
> Set firewall rule `direction` to `ingress` if it's not set

- civo/resource_kubernetes_cluster.go
> Fixed error when you sending to scaling a kubernetes cluster

- civo/datasource_loadbalancer.go
Signed-off-by: Vishal Anarse <vishal@civo.com>
> Fix lb enable proxy protocol type

- civo/datasource_kubernetes_cluster.go
- civo/datasource_kubernetes_cluster_test.go
- civo/resource_kubernetes_cluster.go
- civo/resource_kubernetes_cluster_nodepool.go
- civo/resource_kubernetes_cluster_nodepool_test.go
- civo/resource_kubernetes_cluster_test.go
This PR fix the issue https://github.com/civo/terraform-provider-civo/issues/127
> Fixed errors in the Kubernetes resource and remove unnecessary fields

- civo/resource_object_store_credentials.go
> Fix bug in the creation of object store credential

- civo/resource_firewall.go
> Fix error when you try to create a firewall without region

- civo/resource_object_store.go
- examples/resources/civo_object_store/resource.tf
Fix error in the civo_object_store and add more examples #155
> Fix error in the civo_object_store and add more example

- civo/resource_dns_domain_name.go
- civo/resource_dns_domain_record.go
- civo/resource_firewall.go
- civo/resource_firewall_rule.go
- civo/resource_instance.go
- civo/resource_instance_reserved_ip_assignment.go
- civo/resource_kubernetes_cluster.go
- civo/resource_kubernetes_cluster_nodepool.go
- civo/resource_loadbalancer.go.disabled
- civo/resource_network.go
- civo/resource_object_store.go
- civo/resource_object_store_credentials.go
- civo/resource_reserved_ip.go
- civo/resource_snapshot.go.disabled
- civo/resource_ssh.go
- civo/resource_volume.go
- civo/resource_volume_attachment.go
Fix the error in the firewall, fixed spelling mistakes in the errors and added a new Pending state to the cluster
> Fix the error in the firewall

- civo/datasource_database.go
- civo/datasource_database_test.go
- civo/provider.go
- civo/resource_database.go
- civo/resource_database_test.go
- examples/data-sources/civo_database/data-source.tf
- examples/data-sources/civo_firewall/data-source.tf
- examples/data-sources/civo_instances/data-source.tf
- examples/data-sources/civo_network/data-source.tf
- examples/resources/civo_database/import.sh
- examples/resources/civo_database/resource.tf
- go.mod
- go.sum
Terraform support for Database as a Service
Signed-off-by: satakshigarg <satakshi@civo.com>
> Added support for Database

- civo/resource_kubernetes_cluster.go
- civo/resource_kubernetes_cluster_nodepool.go
> Fixed error when you change the node pool count

- civo/resource_firewall.go
- civo/resource_firewall_test.go
> Add a StateChange to the firewall to wait for network be ready.

- .github/ISSUE_TEMPLATE/bug.yaml
The PR makes  a issue_template to help users to create an issue about the  bug they noticed.
related issue #163
> feat: add bug.yml

- civo/datasource_volume.go
- examples/data-sources/civo_volume/data-source.tf
**Changes:**
1) Adding nil pointer check for volume data source
2) changing spelling mistake for retrieve
3) Adding output in data-source.tf
- **BEFORE** data-source.tf file change it was not displaying any output of volume.
- **AFTER** data-source.tf file change it is displaying returned output- which will be useful for civo terraform users
**Motivation:**
Improve civo terraform project for end users
> [Improvement] Get Volume data-source improvement

- civo/datasource_database.go
- civo/resource_database.go
- examples/data-sources/civo_database_version/data-source.tf
- examples/resources/civo_database/resource.tf
> Fix the doc for database and add extra field

- civo/resource_kubernetes_cluster_nodepool.go
> Remove the waitForKubernetesNodeDelete and add retry to the delete

- .github/workflows/release.yml
> Fix GitHub Actions configuration in release.yml

- .github/workflows/release.yml
> Add environment variable for release job in release.yml

- .github/workflows/release.yml
> Update private key variable in release.yml

- .github/workflows/release.yml
> Update GoReleaser version to 1.25.1 in release.yml

- .github/workflows/release.yml
> Update Go version to 1.21.x in release.yml

- civo/instances/resource_instance.go
> Fix disk_image and public_ip_required in instance read

- civo/network/resource_network.go
> ForceNew on Region in network resource

- civo/network/resource_network.go
Fixes: #221
Adding cidr and nameservers as computed bcz its value get assigned directly by the API if not provided
> Add cidr and Nameservers as computed

- civo/network/resource_network.go
> Create Default firewall for network when not specified.

- civo/instances/resource_instance.go
> Allow updating reserved_ip4 for instance resource

- civo/kubernetes/resource_kubernetes_cluster.go
> Make applications field immutable in clusters

- civo/kubernetes/resource_kubernetes_cluster.go
> Make cluster_type feild immutable in clusters

- civo/kubernetes/resource_kubernetes_cluster.go
> Make Cluster CNI immutable

- examples/resources/civo_instance/resource.tf
This is one small chunk of the work that will cover ticket #224
> Updated the instance documentation example to match all changes

- .github/workflows/ISSUE_TEMPLATE/bug.yml
- .github/workflows/ISSUE_TEMPLATE/feature_request.yml
I am not entirely sure how this is going to look. Changing just two files for now
> Creating better templates to ensure we get better tickets. Issue #301

- civo/firewall/resource_firewall.go
- civo/instances/resource_instance.go
- civo/network/resource_network.go
> Add timeout to resources

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/doc.yml
- .github/ISSUE_TEMPLATE/feature.yml
- .github/ISSUE_TEMPLATE/other.yml
> Fixing some minor issues with the template

- civo/provider.go
- civo/provider_test.go
fixes: #310 
when token is picked from Env Var
------------------------------------------------------------------
when token is picked from CLI
> Flash Error msg upon invalid token in provider def

- civo/firewall/resource_firewall.go
- civo/provider.go
> Validation to set create_default_rules to false when any of the firewall rule is specified

- civo/instances/resource_instance.go
- civo/provider.go
- docs/resources/instance.md
> Make saving initial_password in instance to state  as optional

- civo/kubernetes/resource_kubernetes_cluster.go
- civo/network/resource_network.go
> Do Polling when deleting resources to ensure complete deletation

- docs/resources/kubernetes_cluster.md
need docs to use new property introduced in 1.1.0 of civo provider
> adding documentation for the new write_kubeconfig property

- civo/instances/resource_instance.go
> Add missing instance states

- civo/database/resource_database.go
- docs/resources/database.md
- go.mod
- go.sum
> Addition of privateIP in DB resource

- civo/instances/resource_instance.go
- docs/resources/instance.md
> Make script field immutable for instance resource

- civo/instances/resource_instance.go
- civo/kubernetes/resource_kubernetes_cluster.go
> Ensuring the error message is properly formatted when it contains new lines. (Issue 346)

- civo/dns/resource_dns_domain_record.go
- go.mod
- go.sum
> Added support for NS DNS record

- civo/kubernetes/datasource_kubernetes_cluster.go
- civo/kubernetes/datasource_kubernetes_cluster_test.go
- civo/kubernetes/resource_kubernetes_cluster.go
- civo/kubernetes/resource_kubernetes_cluster_test.go
- civo/volume/datasource_volume.go
- civo/volume/datasource_volume_test.go
- civo/volume/resource_volume_test.go
- go.mod
- go.sum
Adds support for specifying volume_type in k8s clusters
> add support for volume_type in kubernetes clusters
