civo/terraform-provider-civo

doc.md

I'm assuming that "leyend" was supposed to say legend but I'm not sure.

Fix doc.md typo?

---

website/docs/d/kubernetes_version.html.markdown

It should be key, doesn't work with name = "type"

Edit Kubernetes  provider markdown mistype

---

README.md

The official README does not have a valid repository URL and should really be changed to HTTPS

fix(README): Fixed unauthenticated download in README.md

---

docs/data-sources/instance.md
docs/data-sources/instances.md
docs/resources/instance.md

Short fix of the outdated description from the attribute public_ip_requiered to `This should be either `create`, `none` or `move_ip_from:intances_id`

Update attribute public_ip_requiered description.

---

civo/resource_kubernetes_cluster.go
docs/resources/kubernetes_cluster.md

In the civo_kubernetes_cluster's documentation: 
- The example to remove the default Traefik application wouldn't work ("-traefik") because the app names are case sensitive, so it needs to be "-Traefik". 
- I also added a generic mention for case-sensitivity, and a civo CLI example to list the available applications. 
- Also in the HCL example I removed the space after the "," as the application documentation requires it.
I made the doc updates in both the documentation (markdown) file and the provider file (go).

Fixed 'applications' argument's description and corresponding examples.

---

docs/resources/kubernetes_cluster.md

The previous `load_config_file`, `username` and `password` are not working. I'm not sure if they used to work before.
We have to use `client_certificate` and `client_key` together with current `cluster_ca_certificate` now. And they need to be base64 decoded.
References:
- https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#credentials-config
- https://www.terraform.io/docs/language/functions/base64decode.html

Docs update for Kubernetes provider example

---

docs/resources/kubernetes_cluster.md

Add Kubernetes node sizes Data Source and lists in civo_kubernetes_cluster example

---

civo/resource_instance.go

Closes #51
---
`tf show` output **before** this PR
<details>
<summary>Show</summary>
```
resource "civo_instance" "my-test-instance" {
cpu_cores          = 1
created_at         = "0001-01-01 00:00:00 +0000 UTC"
disk_gb            = 15
firewall_id        = "c1ce01cf-5e01-4378-8f03-f93a45d31843"
hostname           = "foo.com"
id                 = "77728c16-40fc-4fa0-87a7-9cc2b50116c3"
initial_password   = "X7TepMCRE5Y4"
initial_user       = "civo"
network_id         = "fb3cdfff-66ba-4048-9f37-8625237cbe67"
notes              = "this is a note for the server"
private_ip         = "192.168.1.11"
public_ip          = "212.2.246.134"
public_ip_required = "create"
ram_mb             = 1024
size               = "g3.k3s.xsmall"
source_id          = "debian-10"
source_type        = "diskimage" …
```

Mark IaaS password as sensitive

---

civo/resource_ssh.go

Marking public key non sensitive

---

civo/resource_instance.go

Closes #53
<details>
<summary>Show outputs when testing this PR</summary>
```
~/civo/test-civo-terraform-provider ᐅ ls -la
total 16
drwxr-xr-x   6 zulh  staff  192 Aug 13 15:49 .
drwxr-xr-x  29 zulh  staff  928 Aug  5 11:31 ..
drwxr-xr-x   3 zulh  staff   96 Aug  9 10:06 .terraform
drwxr-xr-x   3 zulh  staff   96 Aug  9 10:33 .terraform.d
-rw-r--r--   1 zulh  staff  234 Aug 13 15:49 main.tf
-rw-r--r--   1 zulh  staff  355 Aug 13 12:38 provider.tf
~/civo/test-civo-terraform-provider ᐅ cat main.tf
resource "civo_instance" "my-test-instance" {
hostname = "kubeform-test"
tags = ["python", "nginx"]
notes = "this is a note for the server"
template = "8eb48e20-e5db-49fe-9cdf-cc8f381c61c6"
}
~/civo/test-civo-terraform-provider ᐅ tf init
2021-08-13T15:50:12.807+0800 [INFO]  Terraform version: …
```

Fix "empty non-retryable error received" error when updating IaaS node size

---

civo/resource_kubernetes_cluster.go

Closes #57
---
`tf show` output **before** this PR
<details>
<summary>Show</summary>
```
resource "civo_kubernetes_cluster" "my-cluster" {
api_endpoint           = "https://212.2.247.178:6443"
created_at             = "2021-08-13 04:30:40 +0000 UTC"
dns_entry              = "ce0e3a6a-a4e7-4af0-8f7c-37edffc8705e.k8s.civo.com"
id                     = "ce0e3a6a-a4e7-4af0-8f7c-37edffc8705e"
installed_applications = []
instances              = [
{
cpu_cores = 1
disk_gb   = 15
hostname  = "k3s-my-cluster-a4eed495-node-pool-1531"
ram_mb    = 2048
size      = ""
status    = "ACTIVE"
tags      = []
},
{
cpu_cores = 1
disk_gb   = 15
hostname  = "k3s-my-cluster-a4eed495-node-pool-edae"
ram_mb    = 2048
size      = ""
status    = "ACTIVE"
tags      = []
},
{
cpu_cores = 1
disk_gb   = 15
hostname  = …
```

Make 'kubeconfig' field sensitive

---

civo/resource_kubernetes_cluster.go
internal/utils/utils.go

Closes #52 
Also added a validation for `num_target_nodes` field. Only positive number should be accepted moving forward.
Example error when user provide `0` or negative number:

Fix cluster primary nodepool scaling bug

---

civo/resource_volume.go
civo/resource_volume_attachment.go
docs/resources/volume.md

Volumes management

---

civo/resource_firewall_rule.go
civo/resource_kubernetes_cluster.go
go.mod
go.sum

Depends on https://github.com/civo/civogo/pull/60. Close #35.
---
Example configuration file:
```terraform
resource "civo_network" "my_custom_network" {
label  = "my-custom-network"
}
resource "civo_firewall" "my_custom_firewall" {
name       = "my-custom-firewall"
network_id = civo_network.my_custom_network.id
}
resource "civo_firewall_rule" "http" {
firewall_id = civo_firewall.my_custom_firewall.id
protocol    = "tcp"
start_port  = "80"
end_port    = "80"
direction   = "ingress"
label       = "web-server"
depends_on  = [civo_firewall.my_custom_firewall]
}
resource "civo_kubernetes_cluster" "my_cluster" {
name              = "my_cluster"
num_target_nodes  = 1
target_nodes_size = "g3.k3s.medium"
network_id        = civo_network.my_custom_network.id
firewall_id       = …
```

Add firewall support for Kubernetes cluster

---

civo/resource_firewall.go

Close #76 
---
Here is the full logs when I destroy the resources in #76 using this branch. Look for `Unable to find firewall 78d936aa-bd2c-4831-8f91-2df957332f3e - probably it's been deleted` line. It will no longer throw an error.
```
$ tf destroy --auto-approve
2021-08-30T10:07:39.887+0800 [INFO]  Terraform version: 1.0.3
2021-08-30T10:07:39.887+0800 [INFO]  Go runtime version: go1.16.4
2021-08-30T10:07:39.887+0800 [INFO]  CLI args: []string{"/usr/local/bin/terraform", "destroy", "--auto-approve"}
2021-08-30T10:07:39.887+0800 [INFO]  Loading CLI configuration from /Users/zulh/.terraformrc
2021-08-30T10:07:39.888+0800 [INFO]  CLI command args: []string{"destroy", "--auto-approve"}
2021-08-30T10:07:39.964+0800 [INFO]  Failed to read plugin lock file …
```

Check if firewall exists before deleting

---

civo/resource_volume.go

Close #83 
When network does not exist, this error will appear:

Check network before creating volume

---

civo/resource_kubernetes_cluster.go

- Close #95
- Close #97 
When user tries to upgrade their cluster's Kubernetes version, they will get this:

Disable k8s version upgrade

---

.auto-changelog-config
.auto-changelog-template.hbs
.github/workflows/release.yml

Tho trigger this _release_ workflow moving forward, we can use GitHub web UI or [GitHub CLI v2](https://cli.github.com/):
- Go to Actions > Release > Run workflow
- Enter the new version to release e.g. `v0.10.11`
- Click the `Run workflow` button
Run:
```
$ gh workflow run release.yml --repo civo/terraform-provider-civo --field newVersionTag=vX.X.X
```
Example:
```
$ gh workflow run release.yml --repo civo/terraform-provider-civo --field newVersionTag=v0.10.11
```
References:
- https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
- https://cli.github.com/manual/gh_workflow_run

GitHub Actions - Auto generate changelog and docs when publish a new release

---

civo/provider.go

This PR will allow us to use non-production API server URL e.g. staging/dev servers to test our Terraform provider. Here is quick guide for it.
```sh
$ export CIVO_API_URL="https://example.com"
$ tf plan|apply|destroy
```
```sh
$ unset CIVO_API_URL
$ tf plan|apply|destroy
```

Add support to use non-production API server URL

---

civo/resource_firewall.go

As there doesn't appear to be a documented way to update `network_id`,
replace the firewall if the network id changes

Replace the firewall if network id changes

---

civo/datasource_firewall.go
civo/datasource_firewall_test.go
civo/provider.go

With this PR, we should be able to query firewall using datasource, for example,
```
data "civo_firewall" "myfirewall" {
name = "myfirewall"
}
```

Add Data source for `civo_firewall`

---

civo/datasource_firewall.go
examples/data-sources/civo_firewall/data-source.tf

This will update the `civo_firewall` docs and also add the example which will reflect on terraform provider documentation

update docs for datasource civo_firewall

---

civo/provider.go

I was wondering why my clusters with exported env var `CIVO_REGION="FRA1"` were created in `NYC1`. Removing the empty `Default` fixed the issue

fix: remove double default

---

docs/resources/kubernetes_cluster.md
examples/resources/civo_kubernetes_cluster/resource.tf

added missing required argument action in resource civo_firewall_rule
While executing tf plan:
```
╷
│ Error: Missing required argument
│ 
│   on cluster.tf line 16, in resource "civo_firewall_rule" "kubernetes":
│   16: resource "civo_firewall_rule" "kubernetes" {
│ 
│ The argument "action" is required, but
│ no definition was found.
```

`civo_firewall_rule` resource missing required argument action

---

civo/resource_kubernetes_cluster.go

This was reported by a user with this error:
```
│ Error: error waiting for cluster (UUID) to be created: unexpected state 'UPGRADING', wanted target 'ACTIVE'. last error: %!s(<nil>)
```

Add the UPGRADING state to the cluster creation

---

CODEOWNERS
Makefile
README.md
scripts/local.sh

Addition of a script that sets the local version of the civo terraform provider by taking care of:
- create/override the `~/.terraformrc` file
- create the provider.tf in the destination folder with the local version of the provider
- building the binary of the provider from the current branch and moving it into the destination folder
- performing a `terraform init` and a `terraform plan`
The script takes care of checking if golang, civo CLI and terraform are installed.

Adds an init script that uses the local version of the provider

---

civo/datasource_instance.go

**Problem:**
- foundImage is Pointer of civogo.Instance
- In case if GetOk() is not satisfied then both conditions will fail. foundImage  pointer will remain **nil**
- If the pointer is nil then it will give a **memory access violation** for using foundImage.XXX properties.
**Solution:**
- If we are using pointer then need to check for nil value
- If nil value found then return error
**My Changes:**
- Checking foundImage  pointer value is nil or not
- if nil is found then return an error for dataSourceInstanceRead function
- Spelling mistake correction:  retrive --> retrieve

Fix: nil pointer check for instance

---

.github/ISSUE_TEMPLATE/doc.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/other.yml

Create issue templates for various issues like docs, new feature and any other issues.
relates issue #163

feat: add ISSUE_TEMPLATES to report issues

---

civo/resource_network.go

Add WaitForStateto the network delete

---

civo/resource_kubernetes_cluster.go

The list of applications needs to be supplied as comma-separated strings. 
Including spaces breaks the process.
This change should ensure no spaces are passed to the API.
In the current version, this example:
```
resource "civo_kubernetes_cluster" "civo001" {
applications = "metrics-server, traefik2-nodeport, prometheus-operator"
name         = "civo001"
firewall_id  = civo_firewall.civo001.id
cluster_type = "talos"
pools {
size       = "g4s.kube.medium"
node_count = 3
}
}
```
produces the following error:
`Error: [ERR] failed to create the kubernetes cluster: Error: Unknown error response - status: 404 Not Found, code: 404, reason: {"code":"database_kubernetes_aplication_not_found","reason":"Failed to find the Kubernetes application for installation"}`
Removing the spaces in the …

Remove spaces in the applications string

---

civo/network/resource_network.go
examples/data-sources/civo_network/data-source.tf

Add CIDR and Nameservers support in network

---

civo/instances/resource_instance.go

If user does any such change then we can do a destroy and create replacement. This would destroy the current present instance and create a new one. with the updated disk image.

Destory and Re-create Instance in case of disk-image update

---

civo/instances/resource_instance.go

Fixes: #225 
Fixes: #223 
Fixes: #222 
Fixes: #220 
------------------------------------
------------------------------------
------------------------------------
Updating SSH Key of an pre-existing instance is not supported by Civo

Various improvements in `civo_instance` rersource

---

civo/instances/resource_instance.go

Change firewall ID to be a required field

---

civo/instances/resource_instance.go
civo/network/resource_network.go

Check for Resource Already Exist Error before retry

---

civo/network/resource_network.go

Fixes: #233 
Since CIDR is immutable via API, applying the same over here. 
The `CustomizeDiff`  function allows us to perform custom validation during the diff phase and can be used to detect changes to the `cidr_v4`  field and return an error if a change is detected.
This would throw an error in the planning phase itself.
The below change will throw error error when terraform apply is done hence this approach is not preferable.
```
func resourceNetworkUpdate(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
apiClient := m.(*civogo.Client)
// overwrite the region if is defined in the datasource
if region, ok := d.GetOk("region"); ok {
apiClient.Region = region.(string)
}
if d.HasChange("cidr_v4") {
return diag.Errorf("the 'cidr_v4' field is immutable")
}
if …
```

Make CIDR immutable for network resource

---

civo/instances/resource_instance.go

Fixes: #252 
To address this issue, we can implement dependencies explicitly in the Terraform configuration using the depends_on argument. This argument will make sure the reserved IP is destroyed after the instance.
```
provider "civo" {
region = "LON1"
}
resource "civo_reserved_ip" "www" {
name = "test-ip2"
}
resource "civo_instance" "foo" {
hostname = "amazingthingy20"
tags = ["python", "nginx"]
notes = "This is a test-issue"
size = "g3.xsmall"
region = "LON1"
reserved_ipv4 = civo_reserved_ip.www.id
firewall_id = "default-default"
disk_image = "debian-10"
depends_on = [civo_reserved_ip.www]
}
```
Also i've made changes in the provider to ensure that when an instance is deleted, it properly waits for the deletion to be completed this will solve the issue

Wait for the instance to be completely deleted

---

civo/instances/resource_instance.go

fixes: #247 
As it is an immutable field via api, an replacement prompt will occur when change in this value is detected.

change in private_ipv4 on instance value requires the replacement

---

civo/instances/resource_instance.go
civo/network/resource_network.go
internal/utils/utils.go

This PR fixes #263 
Fixes: #256
fixes: #269 
fixes: #271 
fixes: #273 
fixes: #270
Now we directly return the error received from the API, instead of retrying.
I have also added functions to parse the error received and return only the error code and associated message to the user.
It also fixes issues: 256, 249, 269, 271, 273.
This will likely fix 270 as well.
Screenshots from the Result:
Issue 263:
Issue 256:
Issue 249:
Issue 269:
Issue 271:
Issue 273:

fix: remove unnecessary retries and improve error handling

---

civo/kubernetes/resource_kubernetes_cluster.go

This PR fixes #261 
**Screenshots:**
Current Behaviour:
Says modification applied:
But cluster's state remains the same:
`main.tf`:
After changes:
Cluster updating:
Cluster updated with a new `kubernetes_version`:

fix: allow updating kubernetes_version after cluster creation

---

civo/kubernetes/resource_kubernetes_cluster.go
internal/utils/utils.go

This PR fixes #277 
In here:
I added validation for the `cluster_type` attribute to ensure it only accepts `k3s` or `talos`. This prevents defaulting to `k3s` when an invalid value is provided.
Result:

fix: validate cluster_type to ensure it is either 'k3s' or 'talos'

---

civo/kubernetes/resource_kubernetes_cluster.go
go.mod
go.sum

This PR fixes #262 
In here,
1. The provider was using `civogo` version `v0.3.70`, and now has been updated to `v0.3.73` to pull the latest changes necessary to fix this issue.
2. The code also updates the cluster's configuration with the new `firewall_id`, allowing users to update post creation.
Screenshots:
Created with `my-firewall`:
Modification to `firewall_id` successfully applied:
Post update, using `my-firewall2`:

fix: support updating firewall_id for civo_kubernetes_cluster

---

civo/network/resource_network.go

Support to update network nameservers

---

civo/kubernetes/resource_kubernetes_cluster.go

This PR fixes #284 
The changes ensure that application plans with spaces (e.g., 'Linkerd with Dashboard & Jaeger') are correctly processed in the Terraform provider, matching the behavior of the CLI.
Result:
`main.tf`:
Successful resource Creation:
Dashboard correctly showing the applications installed:

fix: handle application plans with spaces

---

civo/provider.go
civo/provider_test.go
examples/provider/provider.tf
scripts/local.sh

This pull request introduces the feature requested in #246 
It Implements a priority-based token retrieval:
1. Environment variable (CIVO_TOKEN).
2. Token provided via a Credential file.
3. Lastly, fall back to CLI config file (~/.civo.json)
**Tests'  Screenshots:**
I have introduced coloured debug messages(removed from the main code), which correctly prints the token it abstracts:
Below, I have set the token using Civo CLI command `civo apikey save CIVO_TOKEN clitoken96` which saves it in `~/.civo.json`.
You can see, it correctly prints a different token(last coloured debug message):

Feat: fallback to CLI config for token

---

civo/kubernetes/resource_kubernetes_cluster.go
go.mod
go.sum
internal/utils/utils.go

This PR fixes #296 
In here,
1. I introduced a new boolean configuration `write_kubeconfig` to control whether the kubeconfig is written to the Terraform state.
2. Defaulted `write_kubeconfig` to false.
3. Added a warning message to inform users about the new behavior. It flashes when users' provider version is `<=1.0.49`(current one)
**I tested again, and here are the results:**
`main.tf`: no `write_kubeconfig` specified.
correctly defaulting to `false`:
successful resource creation:
`kubeconfig` rightly hidden:
updating configuration:
correctly planned:
Update successful:
`kubeconfig` rightly written to state:
Updating again:

Make saving kubeconfig to state optional for civo_kubernetes resource

---

civo/kubernetes/resource_kubernetes_cluster.go
docs/resources/kubernetes_cluster.md

Based on some feedback in the community we discovered it would be more helpful to clarify that the latest k8s version if unspecified is not just the latest available but additionally is the latest **stable** as well within a given cluster type if version is not specified.
```c
date && civo k8s versions
Tue Aug 13 03:34:15 PM EDT 2024
+--------------+--------------+--------------+-------------+---------+
| Name         | K8s version  | Cluster-Type | Maturity    | Default |
+--------------+--------------+--------------+-------------+---------+
| 1.27.11-k3s1 | 1.27.11-k3s1 | k3s          | deprecated  | false   |
+--------------+--------------+--------------+-------------+---------+
| talos-v1.2.8 | 1.25.5       | talos        | deprecated  | false   | …
```

default k8s version is latest stable available

---

civo/provider.go
go.mod
go.sum
internal/utils/utils.go

This PR fixes #316 
In here, I:
- Added checks for the existence of the credentials_file provided by the user.
- Validated the correct data structure of the token file.
- Implemented a file size limit check to prevent issues with excessively large files.
Result:
Some error scenarios:

fix: validate existence and structure of credentials_file

---

civo/kubernetes/resource_kubernetes_cluster.go

Here its necessary to set `firewall_id` in the `d.HasChange("write_kubeconfig")` block so that in case where only `write_kubeconfig` is changed we do not pass on an empty config struct in the update API call and it will fail.
And since firewall is a required field. It does no harm in sending it as an update

Honouring write_kubeconfig post cluster creation

---

civo/kubernetes/resource_kubernetes_cluster.go

This PR fixes #327 
In Here, I: 
- Introduced a separate field for specifying minimum Kubernetes version.
- Added support for version string permutations.
- Improved error messages for invalid version formats.

Fix: Enhance Kubernetes version handling

---

docs/index.md
docs/resources/instance.md
docs/resources/kubernetes_cluster.md

No ticket was assigned to this.

Adding some documentation changes to clarify additional features

---

civo/kubernetes/resource_kubernetes_cluster.go

Fixes #352 
Result:
`main.tf`:
Correctly throwing error:
Updated the version string:
Resource getting created successfully:

honor Talos version string when creating clusters

---

civo/kubernetes/resource_kubernetes_cluster.go

validation check for CNI and cluster type

---

civo/kubernetes/datasource_kubernetes_version.go
go.sum

This fixes #366.
**Before:**
**After:**

Fix: Fetch correct label from kubernetes version datasource for talos cluster

---

civo/volume/resource_volume_attachment.go
civo/volume/resource_volume_attachment_test.go

`attach_on_boot` is used in the `resource_volume_attachment` but isn't defined in the schema

add attach_on_boot to the resource_volume_attachement schema

---

docs/resources/instance_reserved_ip_assignment.md
docs/resources/reserved_ip.md

When using `civo_instance_reserved_ip_assignment` resource to assign a reserved IP address to a `civo_instance` subsequent resources are not able to use it’s `public_ip` attribute, because it is empty.
For example, the following Terraform code snippet creates a reserved ip and an instance, and using `civo_instance_reserved_ip_assignment` resource assign the public IP to the instance. Resources that relay on instance public ip attribute, such as outputting instance IP address, fail. This PR adds a disclaimer and alternative solution.
```bash
resource "civo_reserved_ip" "this" {
...
}
resource "civo_instance" "this" {
...
}
resource "civo_instance_reserved_ip_assignment" "webserver-www" {
instance_id    = civo_instance.this.id
reserved_ip_id = civo_reserved_ip.this.id
}
output …
```

docs: interaction between instances and reserved ip
